In [1]:
import pandas as pd

In [3]:
train_df=pd.read_csv('nlp_start/train.csv')
test_df=pd.read_csv('nlp_start/test.csv')

In [5]:
train_df.tail()

id keyword location  \
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1

In [7]:
train_df.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [8]:
train_df.shape

(7613, 5)

In [11]:
train_df['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [ ]:
train_shuffle=train_df.sample(frac=1,random_state=49) 
train_shuffle.head(20)

In [17]:
print(f"Total train samples: {len(train_df)}")
print(f"Total test samples: {len(test_df)}")
print(f"Total  samples: {len(train_df)+len(test_df)}")

Total train samples: 7613
Total test samples: 3263
Total  samples: 10876


In [ ]:
import random

random_index=random.randint(0, len(train_df)-4)

for row in train_shuffle[['text','target']][random_index:random_index+4].itertuples():
    print(row)


In [22]:
from sklearn.model_selection import train_test_split

train_sentences, test_sentences, train_labels,test_labels = train_test_split(
    train_shuffle['text'].to_numpy(),
    train_shuffle['target'].to_numpy(),
    test_size=0.1, 
    random_state=49
)

In [24]:
train_sentences.dtype, train_labels.dtype

(dtype('O'), dtype('int64'))

In [27]:
len(train_sentences), len(test_sentences)

(6851, 762)

In [28]:
import tensorflow as tf 
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [35]:
text_vectorizer = TextVectorization(max_tokens=10000, 
                                    standardize="lower_and_strip_punctuation", 
                                    output_sequence_length=15)

In [36]:
text_vectorizer.adapt(train_sentences)

In [37]:
sample_sentense="I Love Tensorflow"

text_vectorizer([sample_sentense])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  8, 107,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0]], dtype=int64)>

In [42]:
words = text_vectorizer.get_vocabulary()



In [43]:
from tensorflow.keras.layers import Embedding

In [44]:
embedding = Embedding(
                        input_dim=10000, 
                        output_dim=128, 
                        input_length=15, 
                        name = 'embeding_1'
)

In [45]:
embedding

In [46]:
sample_embed = embedding(text_vectorizer("I Love Tensorflow"))
sample_embed

<tf.Tensor: shape=(15, 128), dtype=float32, numpy=
array([[ 0.01231587, -0.00256255,  0.04978896, ...,  0.0468483 ,
        -0.01590898, -0.03175728],
       [-0.01817663, -0.04545405, -0.03042921, ...,  0.02274327,
        -0.0182047 , -0.01355995],
       [-0.01948857,  0.00554798,  0.03427506, ...,  0.03786555,
        -0.03715464, -0.02071316],
       ...,
       [ 0.03924679,  0.02573956,  0.03817136, ..., -0.00771222,
        -0.02599858,  0.01145264],
       [ 0.03924679,  0.02573956,  0.03817136, ..., -0.00771222,
        -0.02599858,  0.01145264],
       [ 0.03924679,  0.02573956,  0.03817136, ..., -0.00771222,
        -0.02599858,  0.01145264]], dtype=float32)>