In [1]:
import pandas as pd

In [2]:
train_df=pd.read_csv('nlp_start/train.csv')
test_df=pd.read_csv('nlp_start/test.csv')

In [3]:
train_df.tail()

id keyword location  \
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1

In [4]:
train_df.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [5]:
train_df.shape

(7613, 5)

In [6]:
train_df['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [7]:
train_shuffle=train_df.sample(frac=1,random_state=49) 
train_shuffle.head(20)

id      keyword                  location  \
74     107     accident            North Carolina   
5387  7687        panic                   Toronto   
4259  6051  heat%20wave   Arnhem, the Netherlands   
2119  3045        death       Home of the Takers.   
6078  8684     sinkhole           Haddonfield, NJ   
37      55       ablaze              World Wide!!   
2118  3044        death         Carry On Jutta!!!   
3931  5589        flood                       NaN   
530    770    avalanche       South Central Wales   
4186  5947       hazard   a van down by the river   
125    180   aftershock                       304   
314    457   armageddon                    Canada   
3396  4860   evacuation    Moncton, New Brunswick   
6179  8815       sirens                    Sydney   
108    158   aftershock  Instagram - @heyimginog    
4        7          NaN                       NaN   
5689  8119      rescued                       NaN   
6866  9838       trauma             Nashville, TN   
6860  9832       trauma           Little Rock, AR   
6231  8896    snowstorm                       NaN   

                                                   text  target  
74    I-77 Mile Marker 31 South Mooresville  Iredell...       1  
5387  tomorrow's going to be a year since I went to ...       1  
4259  Arnhem Weather - &lt;p&gt;An unrelenting and d...       1  
2119       Y'all PUSSSSSSSSSY AND SHOOOK TO DEATH OF ME       0  
6078  Georgia sinkhole closes road swallows whole po...       1  
37    INEC Office in Abia Set Ablaze - http://t.co/3...       1  
2118  Afghan peace talks in doubt after Mullah Omar'...       0  
3931  Internet basics: the flood defective intertiss...       1  
530   I saw two great punk bands making original mus...       0  
4186  @phiddleface NOT IF THERES A CHOKING HAZARD!!!...       0  
125   Sometimes you face difficulties not because yo...       0  
314   @ENews Ben Affleck......I know there's a wife/...       0  
3396  Gas leak forces evacuation in east Saint John ...       1  
6179  Marketforce Perth named winner of Sirens round...       0  
108   @afterShock_DeLo im speaking from someone that...       0  
4     Just got sent this photo from Ruby #Alaska as ...       1  
5689  @BrittanyPetko breaking news tonight kids were...       1  
6866  Esteemed journalist recalls tragic effects of ...       1  
6860  @thetimepast @saalon I have childhood trauma m...       0  
6231  Hi yall this poem is called is the one about t...       0

In [8]:
print(f"Total train samples: {len(train_df)}")
print(f"Total test samples: {len(test_df)}")
print(f"Total  samples: {len(train_df)+len(test_df)}")

Total train samples: 7613
Total test samples: 3263
Total  samples: 10876


In [9]:
import random

random_index=random.randint(0, len(train_df)-4)

for row in train_shuffle[['text','target']][random_index:random_index+4].itertuples():
    print(row)


Pandas(Index=1765, text='my favorite lady came to our volunteer meeting\nhopefully joining her youth collision and i am excite http://t.co/Ij0wQ490cS', target=1)
Pandas(Index=139, text='Experts in France begin examining airplane debris found on Reunion Island: French air accident experts on Wedn... http://t.co/bKpFpOGySI', target=1)
Pandas(Index=3564, text="I've experienced the smell of rotting potatoes for the first time. The Famine must have been awful if the whole country smelled like that.", target=1)
Pandas(Index=6894, text='@disneyIrh so traumatised im ???? http://t.co/TATZfK63Ch', target=1)


In [10]:
from sklearn.model_selection import train_test_split

train_sentences, test_sentences, train_labels,test_labels = train_test_split(
    train_shuffle['text'].to_numpy(),
    train_shuffle['target'].to_numpy(),
    test_size=0.1, 
    random_state=49
)

In [11]:
train_sentences.dtype, train_labels.dtype

(dtype('O'), dtype('int64'))

In [12]:
len(train_sentences), len(test_sentences)

(6851, 762)

In [13]:
import tensorflow as tf 
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [14]:
text_vectorizer = TextVectorization(max_tokens=10000, 
                                    standardize="lower_and_strip_punctuation", 
                                    output_sequence_length=15)

In [15]:
text_vectorizer.adapt(train_sentences)

In [16]:
sample_sentense="I Love Tensorflow"

text_vectorizer([sample_sentense])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  8, 107,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0]], dtype=int64)>

In [17]:
words = text_vectorizer.get_vocabulary()



In [18]:
from tensorflow.keras.layers import Embedding

In [19]:
embedding = Embedding(
                        input_dim=10000, 
                        output_dim=128, 
                        input_length=15, 
                        name = 'embeding_1'
)

In [20]:
embedding

In [21]:
sample_embed = embedding(text_vectorizer("I Love Tensorflow"))
sample_embed

<tf.Tensor: shape=(15, 128), dtype=float32, numpy=
array([[ 0.04459265, -0.01684532,  0.02759372, ..., -0.04119661,
         0.03914695, -0.02494565],
       [ 0.01291105,  0.00410497, -0.00692033, ..., -0.0049533 ,
         0.0152256 ,  0.01226714],
       [ 0.02960142, -0.01097136, -0.04539039, ...,  0.04619695,
        -0.03740982,  0.00810456],
       ...,
       [ 0.01519274, -0.02291369,  0.01295135, ..., -0.03606644,
         0.02298403,  0.00444556],
       [ 0.01519274, -0.02291369,  0.01295135, ..., -0.03606644,
         0.02298403,  0.00444556],
       [ 0.01519274, -0.02291369,  0.01295135, ..., -0.03606644,
         0.02298403,  0.00444556]], dtype=float32)>