In [33]:
import tensorflow as tf

In [34]:
a = tf.constant([3,7,3,2,14,20])
b = tf.constant([5,6,7,10,82,19])
print(a)
print(b)

tf.Tensor([ 3  7  3  2 14 20], shape=(6,), dtype=int32)
tf.Tensor([ 5  6  7 10 82 19], shape=(6,), dtype=int32)


In [8]:
# Multiply
mult_ab = tf.multiply(a, b)


In [10]:
# Dot product
dot_ab = tf.tensordot(a, b, 1)

In [21]:
# Matrix
m1 = tf.reshape(a,[2,3])
m2 = tf.reshape(b,[3,2])

In [22]:
m1,m2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 3,  7,  3],
        [ 2, 14, 20]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 5,  6],
        [ 7, 10],
        [82, 19]], dtype=int32)>)

In [25]:
tf.matmul(m1,m2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 310,  145],
       [1748,  532]], dtype=int32)>

In [32]:
import pandas as pd
data=pd.read_csv('lab1_task2.csv')
data=tf.convert_to_tensor(data)
data

<tf.Tensor: shape=(7, 7), dtype=float64, numpy=
array([[ 1.40000000e+01,  2.00000000e+00,  3.40490000e+00,
        -1.40490000e+00,  1.97374401e+00,  1.97374401e+00,
         1.40490000e+00],
       [ 1.60000000e+01,  5.00000000e+00,  3.89250000e+00,
         1.10750000e+00,  1.22655625e+00,  1.60015013e+00,
         1.25620000e+00],
       [ 2.70000000e+01,  7.00000000e+00,  6.57430000e+00,
         4.25700000e-01,  1.81220490e-01,  1.12717358e+00,
         9.79366667e-01],
       [ 4.20000000e+01,  9.00000000e+00,  1.02313000e+01,
        -1.23130000e+00,  1.51609969e+00,  1.22440511e+00,
         1.04235000e+00],
       [ 3.90000000e+01,  1.00000000e+01,  9.49990000e+00,
         5.00100000e-01,  2.50100010e-01,  1.02954409e+00,
         9.33900000e-01],
       [ 5.00000000e+01,  1.30000000e+01,  1.21817000e+01,
         8.18300000e-01,  6.69614890e-01,  9.69555890e-01,
         9.14633333e-01],
       [ 8.30000000e+01,  2.00000000e+01,  2.02271000e+01,
        -2.27100000e-01,  5.1

In [27]:
import numpy as np
import tensorflow.experimental.numpy as tnp


In [30]:
tnp.experimental_enable_numpy_behavior()
ones = tnp.ones([5, 3], dtype=tnp.float32)
print("Created ND array with shape = %s, rank = %s, "
      "dtype = %s" % (
          ones.shape, ones.ndim, ones.dtype))

Created ND array with shape = (5, 3), rank = 2, dtype = <dtype: 'float32'>
